name: Release

on:
  push:
    tags:
      - 'v*'   # Trigger this workflow when pushing tags like v1.0.0, v2.3.4

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build project
        run: |
          mkdir dist
          echo "Pretend this is a compiled binary" > dist/my-app.txt

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
